import React from 'react';
import {ScrollView, Text, View, ImageBackground, Image} from 'react-native';
import styles from './style';
import {IVideo} from '../MyWoorldOriginals/MyWoorldOriginals';
import {API_URL} from '../../../constants';

interface IVideoGallery {
  title: string;
  videos: IVideo[];
}
const vds = [
  {
    ID: '1',
    USER_NAME: 'POLVO_MISERIA',
    DATE_POSTED: '2021-01-27',
    DELETED: 'NO',
    TITLE: 'No ser esclavo del enojo',
    DESCRIPTION: '',
    PODCAST: 'Assets/Podcasts/Podcast/enojo.mp3',
    IMAGE: 'Assets/Podcasts/Image/enojo.jpg',
    PRIVACY: 'PUBLIC',
    IN_LIVE: '',
    BROADCASTER_KEY: '',
    PLAYS: '148',
    FORMAT: 'CLIP',
    CATEGORY: '',
    LISTENED: '',
  },
  {
    ID: '2',
    USER_NAME: 'POLVO_MISERIA',
    DATE_POSTED: '2021-01-27',
    DELETED: 'NO',
    TITLE: 'Se libre del miedo',
    DESCRIPTION: 'TRENDING',
    PODCAST: 'Assets/Podcasts/Podcast/miedo.mp3',
    IMAGE: 'Assets/Podcasts/Image/Miedo.jpg',
    PRIVACY: 'PUBLIC',
    IN_LIVE: '',
    BROADCASTER_KEY: '',
    PLAYS: '40',
    FORMAT: 'CLIP',
    CATEGORY: '',
    LISTENED: '',
  },
  {
    ID: '3',
    USER_NAME: 'POLVO_MISERIA',
    DATE_POSTED: '2021-01-27',
    DELETED: 'NO',
    TITLE: 'No caer en la obsecion corporal',
    DESCRIPTION: '',
    PODCAST: 'Assets/Podcasts/Podcast/estetica.mp3',
    IMAGE: 'Assets/Podcasts/Image/estetica.jpg',
    PRIVACY: 'PUBLIC',
    IN_LIVE: '',
    BROADCASTER_KEY: '',
    PLAYS: '117',
    FORMAT: 'CLIP',
    CATEGORY: '',
    LISTENED: '',
  },
  {
    ID: '4',
    USER_NAME: 'POLVO_MISERIA',
    DATE_POSTED: '2021-01-27',
    DELETED: 'NO',
    TITLE: 'Narcisismo',
    DESCRIPTION: 'TRENDING',
    PODCAST: 'Assets/Podcasts/Podcast/narsicismo.mp3',
    IMAGE: 'Assets/Podcasts/Image/Narcisismo.jpg',
    PRIVACY: 'PUBLIC',
    IN_LIVE: '',
    BROADCASTER_KEY: '',
    PLAYS: '105',
    FORMAT: 'CLIP',
    CATEGORY: '',
    LISTENED: '',
  },
  {
    ID: '5',
    USER_NAME: 'POLVO_MISERIA',
    DATE_POSTED: '2021-01-27',
    DELETED: 'NO',
    TITLE: 'La Perfeccion',
    DESCRIPTION: '',
    PODCAST: 'Assets/Podcasts/Podcast/perfeccion.mp3',
    IMAGE: 'Assets/Podcasts/Image/perfeccionismo.jpg',
    PRIVACY: 'PUBLIC',
    IN_LIVE: '',
    BROADCASTER_KEY: '',
    PLAYS: '33',
    FORMAT: 'CLIP',
    CATEGORY: '',
    LISTENED: '',
  },
  {
    ID: '6',
    USER_NAME: 'POLVO_MISERIA',
    DATE_POSTED: '2021-01-27',
    DELETED: 'NO',
    TITLE: 'Un recipiente vacio hace ruido..!!',
    DESCRIPTION: 'TRENDING',
    PODCAST: 'Assets/Podcasts/Podcast/presuncion.mp3',
    IMAGE: 'Assets/Podcasts/Image/presuncion.jpg',
    PRIVACY: 'PUBLIC',
    IN_LIVE: '',
    BROADCASTER_KEY: '',
    PLAYS: '24',
    FORMAT: 'CLIP',
    CATEGORY: '',
    LISTENED: '',
  },
  {
    ID: '7',
    USER_NAME: 'POLVO_MISERIA',
    DATE_POSTED: '2021-01-27',
    DELETED: 'NO',
    TITLE: 'No seas sentimental..',
    DESCRIPTION: '',
    PODCAST: 'Assets/Podcasts/Podcast/sentimentalismo.mp3',
    IMAGE: 'Assets/Podcasts/Image/sentimental.jpg',
    PRIVACY: 'PUBLIC',
    IN_LIVE: '',
    BROADCASTER_KEY: '',
    PLAYS: '37',
    FORMAT: 'CLIP',
    CATEGORY: '',
    LISTENED: '',
  },
  {
    ID: '8',
    USER_NAME: 'POLVO_MISERIA',
    DATE_POSTED: '2021-01-27',
    DELETED: 'NO',
    TITLE: 'No! solo  las drogas son un vicio',
    DESCRIPTION: '',
    PODCAST: 'Assets/Podcasts/Podcast/adicionTV.mp3',
    IMAGE: 'Assets/Podcasts/Image/tvAdiccion.jpg',
    PRIVACY: 'PUBLIC',
    IN_LIVE: '',
    BROADCASTER_KEY: '',
    PLAYS: '26',
    FORMAT: 'CLIP',
    CATEGORY: '',
    LISTENED: '',
  },
  {
    ID: '36',
    USER_NAME: 'EDDIE_MURO',
    DATE_POSTED: '2021-12-28',
    DELETED: 'NO',
    TITLE: 'Por que los milenials evitan compromisos?',
    DESCRIPTION: '',
    PODCAST: 'Assets/Podcasts/Podcast/livePodcast.mp3',
    IMAGE: 'Assets/Podcasts/Image/61cbdd8da0dd4new_generations_1.png',
    PRIVACY: 'PUBLIC',
    IN_LIVE: '',
    BROADCASTER_KEY: '',
    PLAYS: '144',
    FORMAT: 'CLIP',
    CATEGORY: '',
    LISTENED: '',
  },
  {
    ID: '37',
    USER_NAME: 'EDDIE_MURO',
    DATE_POSTED: '2021-12-28',
    DELETED: 'NO',
    TITLE: 'La pareja & descendencia no son la felicidad?',
    DESCRIPTION: '',
    PODCAST: 'Assets/Podcasts/Podcast/livePodcast (1).mp3',
    IMAGE: 'Assets/Podcasts/Image/61cbe0d8f1820podcast-2.png',
    PRIVACY: 'PUBLIC',
    IN_LIVE: '',
    BROADCASTER_KEY: '',
    PLAYS: '87',
    FORMAT: 'CLIP',
    CATEGORY: '',
    LISTENED: '',
  },
  {
    ID: '38',
    USER_NAME: 'EDDIE_MURO',
    DATE_POSTED: '2021-12-28',
    DELETED: 'NO',
    TITLE: 'Mujeres Interesantes?  ',
    DESCRIPTION: '',
    PODCAST: 'Assets/Podcasts/Podcast/livePodcast (2).mp3',
    IMAGE: 'Assets/Podcasts/Image/61cbe9fed2632podcast-3.png',
    PRIVACY: 'PUBLIC',
    IN_LIVE: '',
    BROADCASTER_KEY: '',
    PLAYS: '148',
    FORMAT: 'CLIP',
    CATEGORY: '',
    LISTENED: '',
  },
  {
    ID: '39',
    USER_NAME: 'EDDIE_MURO',
    DATE_POSTED: '2021-12-28',
    DELETED: 'NO',
    TITLE: 'Hijos un obstructor para alcanzar metas?',
    DESCRIPTION: '',
    PODCAST: 'Assets/Podcasts/Podcast/livePodcast (3).mp3',
    IMAGE: 'Assets/Podcasts/Image/61cbf3d236476podcast-5.png',
    PRIVACY: 'PUBLIC',
    IN_LIVE: '',
    BROADCASTER_KEY: '',
    PLAYS: '71',
    FORMAT: 'CLIP',
    CATEGORY: '',
    LISTENED: '',
  },
  {
    ID: '40',
    USER_NAME: 'EDDIE_MURO',
    DATE_POSTED: '2021-12-29',
    DELETED: 'NO',
    TITLE: 'Como trascender en la vida? Fe? Hijos? Legado? ',
    DESCRIPTION: '',
    PODCAST: 'Assets/Podcasts/Podcast/livePodcast (4).mp3',
    IMAGE: 'Assets/Podcasts/Image/61cd18eb04f53podcast-5.png',
    PRIVACY: 'PUBLIC',
    IN_LIVE: '',
    BROADCASTER_KEY: '',
    PLAYS: '157',
    FORMAT: 'CLIP',
    CATEGORY: '',
    LISTENED: '',
  },
  {
    ID: '42',
    USER_NAME: 'EDDIE_MURO',
    DATE_POSTED: '2022-01-03',
    DELETED: 'NO',
    TITLE: 'Como Canalizas Tu Dolor?',
    DESCRIPTION: '',
    PODCAST: 'Assets/Podcasts/Podcast/livePodcast (6).mp3',
    IMAGE: 'Assets/Podcasts/Image/61d377c17697fpodcast-7.png',
    PRIVACY: 'PUBLIC',
    IN_LIVE: '',
    BROADCASTER_KEY: '',
    PLAYS: '57',
    FORMAT: 'CLIP',
    CATEGORY: '',
    LISTENED: '',
  },
  {
    ID: '47',
    USER_NAME: 'LALO_MURO',
    DATE_POSTED: '2022-03-06',
    DELETED: 'NO',
    TITLE: 'Amar Sin Apego',
    DESCRIPTION: '',
    PODCAST: 'Assets/Podcasts/Podcast/6225590045bbdAmar_Sin_Apegos.mp3',
    IMAGE: 'Assets/Podcasts/Image/622559004e8bdamar_sin_apegos.jpeg',
    PRIVACY: 'PUBLIC',
    IN_LIVE: '',
    BROADCASTER_KEY: '',
    PLAYS: '41',
    FORMAT: 'CLIP',
    CATEGORY: '',
    LISTENED: '',
  },
  {
    ID: '48',
    USER_NAME: 'LALO_MURO',
    DATE_POSTED: '2022-03-06',
    DELETED: 'NO',
    TITLE: 'No Haz Sanado?',
    DESCRIPTION: '',
    PODCAST: 'Assets/Podcasts/Podcast/62255c4dd5802No_He_Sanado.mp3',
    IMAGE: 'Assets/Podcasts/Image/62255c4ddbdfdNo_He_Sanado.jpeg',
    PRIVACY: 'PUBLIC',
    IN_LIVE: '',
    BROADCASTER_KEY: '',
    PLAYS: '40',
    FORMAT: 'CLIP',
    CATEGORY: '',
    LISTENED: '',
  },
  {
    ID: '49',
    USER_NAME: 'LALO_MURO',
    DATE_POSTED: '2022-03-06',
    DELETED: 'NO',
    TITLE: 'Como Reconocer Ha Un Narcisista?',
    DESCRIPTION: '',
    PODCAST: 'Assets/Podcasts/Podcast/62255db8d9d6creconocer_al_Narcisista.mp3',
    IMAGE: 'Assets/Podcasts/Image/62255db8ed17fnarcisista.jpeg',
    PRIVACY: 'PUBLIC',
    IN_LIVE: '',
    BROADCASTER_KEY: '',
    PLAYS: '32',
    FORMAT: 'CLIP',
    CATEGORY: '',
    LISTENED: '',
  },
  {
    ID: '50',
    USER_NAME: 'LALO_MURO',
    DATE_POSTED: '2022-03-06',
    DELETED: 'NO',
    TITLE: 'Relacion Toxica? O Sindrome de Estocolmo?',
    DESCRIPTION: 'TRENDING',
    PODCAST:
      'Assets/Podcasts/Podcast/6225613b433f1Relacion_Toxica_Adictiva.mp3',
    IMAGE: 'Assets/Podcasts/Image/6225613b50769toxic.jpeg',
    PRIVACY: 'PUBLIC',
    IN_LIVE: '',
    BROADCASTER_KEY: '',
    PLAYS: '38',
    FORMAT: 'CLIP',
    CATEGORY: '',
    LISTENED: '',
  },
  {
    ID: '51',
    USER_NAME: 'roberto_martinez',
    DATE_POSTED: '2022-06-20',
    DELETED: 'NO',
    TITLE: 'Tus frutos son la persona que eres',
    DESCRIPTION: '',
    PODCAST: 'Assets/Podcasts/Podcast/62b0c77a663aclos-frutos-de-personas.mp3',
    IMAGE: 'Assets/Podcasts/Image/62b0c77a697ablos-frutos-de-personas.png',
    PRIVACY: 'PUBLIC',
    IN_LIVE: '',
    BROADCASTER_KEY: '',
    PLAYS: '93',
    FORMAT: 'CLIP',
    CATEGORY: '',
    LISTENED: '',
  },
  {
    ID: '52',
    USER_NAME: 'diego_dreyfus',
    DATE_POSTED: '2022-06-20',
    DELETED: 'NO',
    TITLE: 'Romperse para crecer',
    DESCRIPTION: '',
    PODCAST: 'Assets/Podcasts/Podcast/62b0cc1d8357cromperce-para-creceer.mp3',
    IMAGE: 'Assets/Podcasts/Image/62b0cc1d84ebcromperce-para-crecer.png',
    PRIVACY: 'PUBLIC',
    IN_LIVE: '',
    BROADCASTER_KEY: '',
    PLAYS: '23',
    FORMAT: 'CLIP',
    CATEGORY: '',
    LISTENED: '',
  },
  {
    ID: '53',
    USER_NAME: 'pinchi_lore',
    DATE_POSTED: '2022-06-20',
    DELETED: 'NO',
    TITLE: 'Estas soltero..?',
    DESCRIPTION: '',
    PODCAST: 'Assets/Podcasts/Podcast/62b0d23e97973estar-soltero.mp3',
    IMAGE: 'Assets/Podcasts/Image/62b0d23e9822bestar-soltero.png',
    PRIVACY: 'PUBLIC',
    IN_LIVE: '',
    BROADCASTER_KEY: '',
    PLAYS: '39',
    FORMAT: 'CLIP',
    CATEGORY: '',
    LISTENED: '',
  },
  {
    ID: '54',
    USER_NAME: 'cesar_lozano',
    DATE_POSTED: '2022-06-20',
    DELETED: 'NO',
    TITLE: 'Como Dejar la amargura?',
    DESCRIPTION: '',
    PODCAST: 'Assets/Podcasts/Podcast/62b0d457e5506amargura.mp3',
    IMAGE: 'Assets/Podcasts/Image/62b0d457e7bd8amargura.png',
    PRIVACY: 'PUBLIC',
    IN_LIVE: '',
    BROADCASTER_KEY: '',
    PLAYS: '32',
    FORMAT: 'CLIP',
    CATEGORY: '',
    LISTENED: '',
  },
  {
    ID: '55',
    USER_NAME: 'daniel_habibf',
    DATE_POSTED: '2022-06-20',
    DELETED: 'NO',
    TITLE: 'El camino a el exito',
    DESCRIPTION: '',
    PODCAST: 'Assets/Podcasts/Podcast/62b0df2d01667camino-exito.mp3',
    IMAGE: 'Assets/Podcasts/Image/62b0df2d048efcamino-exito.jpg',
    PRIVACY: 'PUBLIC',
    IN_LIVE: '',
    BROADCASTER_KEY: '',
    PLAYS: '22',
    FORMAT: 'CLIP',
    CATEGORY: '',
    LISTENED: '',
  },
  {
    ID: '56',
    USER_NAME: 'odin_dupeyron',
    DATE_POSTED: '2022-06-20',
    DELETED: 'NO',
    TITLE: 'No crees fantasias crea realidades!',
    DESCRIPTION: '',
    PODCAST: 'Assets/Podcasts/Podcast/62b0e12c0a279fantasias.mp3',
    IMAGE: 'Assets/Podcasts/Image/62b0e12c1988bfantasias.png',
    PRIVACY: 'PUBLIC',
    IN_LIVE: '',
    BROADCASTER_KEY: '',
    PLAYS: '23',
    FORMAT: 'CLIP',
    CATEGORY: '',
    LISTENED: '',
  },
  {
    ID: '57',
    USER_NAME: 'nilda_chiraviglio',
    DATE_POSTED: '2022-06-20',
    DELETED: 'NO',
    TITLE: 'amar por amor y no por apego',
    DESCRIPTION: '',
    PODCAST: 'Assets/Podcasts/Podcast/62b0e61ccc406amar-sin-apego.mp3',
    IMAGE: 'Assets/Podcasts/Image/62b0e61cd0f7eamar-sin-apego.png',
    PRIVACY: 'PUBLIC',
    IN_LIVE: '',
    BROADCASTER_KEY: '',
    PLAYS: '34',
    FORMAT: 'CLIP',
    CATEGORY: '',
    LISTENED: '',
  },
  {
    ID: '58',
    USER_NAME: 'farid_dieck',
    DATE_POSTED: '2022-06-20',
    DELETED: 'NO',
    TITLE: 'Reflexion: Las dos flechas',
    DESCRIPTION: '',
    PODCAST: 'Assets/Podcasts/Podcast/62b0e7db1a56blas-dos-flechas.mp3',
    IMAGE: 'Assets/Podcasts/Image/62b0e7db1c235las-dos-flechas.png',
    PRIVACY: 'PUBLIC',
    IN_LIVE: '',
    BROADCASTER_KEY: '',
    PLAYS: '29',
    FORMAT: 'CLIP',
    CATEGORY: '',
    LISTENED: '',
  },
  {
    ID: '59',
    USER_NAME: 'luzu_vlogs',
    DATE_POSTED: '2022-06-20',
    DELETED: 'NO',
    TITLE: 'Es Imposible para los que no Creen!',
    DESCRIPTION: '',
    PODCAST: 'Assets/Podcasts/Podcast/62b0ec77bd7baimposible.mp3',
    IMAGE: 'Assets/Podcasts/Image/62b0ec77c0d14imposible.png',
    PRIVACY: 'PUBLIC',
    IN_LIVE: '',
    BROADCASTER_KEY: '',
    PLAYS: '43',
    FORMAT: 'CLIP',
    CATEGORY: '',
    LISTENED: '',
  },
  {
    ID: '60',
    USER_NAME: 'farid_dieck',
    DATE_POSTED: '2022-06-20',
    DELETED: 'NO',
    TITLE: 'el dios de espinoza',
    DESCRIPTION: '',
    PODCAST: 'Assets/Podcasts/Podcast/62b0f569b8599dios-de-espinoza.mp3',
    IMAGE: 'Assets/Podcasts/Image/62b0f569bae21dios-de-espinoza.png',
    PRIVACY: 'PUBLIC',
    IN_LIVE: '',
    BROADCASTER_KEY: '',
    PLAYS: '63',
    FORMAT: 'CLIP',
    CATEGORY: '',
    LISTENED: '',
  },
  {
    ID: '61',
    USER_NAME: 'LALO_MURO',
    DATE_POSTED: '2022-06-20',
    DELETED: 'NO',
    TITLE: 'Te Molesta si te dicen cosas depectivas?',
    DESCRIPTION: 'TRENDING',
    PODCAST: 'Assets/Podcasts/Podcast/62b0ffbbd9aceLGBTQ_Clip_2.mp3',
    IMAGE: 'Assets/Podcasts/Image/62b0ffbc0001arainbow.png',
    PRIVACY: 'PUBLIC',
    IN_LIVE: '',
    BROADCASTER_KEY: '',
    PLAYS: '91',
    FORMAT: 'CLIP',
    CATEGORY: '',
    LISTENED: '',
  },
  {
    ID: '62',
    USER_NAME: 'LALO_MURO',
    DATE_POSTED: '2022-06-20',
    DELETED: 'NO',
    TITLE: 'Todos los gay son travestis?',
    DESCRIPTION: 'TRENDING',
    PODCAST: 'Assets/Podcasts/Podcast/62b1016fe7fe4LGBTQ_Clip_3 .mp3',
    IMAGE: 'Assets/Podcasts/Image/62b1017027046rainbow.png',
    PRIVACY: 'PUBLIC',
    IN_LIVE: '',
    BROADCASTER_KEY: '',
    PLAYS: '25',
    FORMAT: 'CLIP',
    CATEGORY: '',
    LISTENED: '',
  },
  {
    ID: '63',
    USER_NAME: 'LALO_MURO',
    DATE_POSTED: '2022-06-20',
    DELETED: 'NO',
    TITLE: 'Influyen o detonan terceras personas en ser gay?',
    DESCRIPTION: 'TRENDING',
    PODCAST: 'Assets/Podcasts/Podcast/62b10291164fbLGBTQ_Clip_4.mp3',
    IMAGE: 'Assets/Podcasts/Image/62b1029136a19rainbow.png',
    PRIVACY: 'PUBLIC',
    IN_LIVE: '',
    BROADCASTER_KEY: '',
    PLAYS: '96',
    FORMAT: 'CLIP',
    CATEGORY: '',
    LISTENED: '',
  },
  {
    ID: '64',
    USER_NAME: 'LALO_MURO',
    DATE_POSTED: '2022-06-20',
    DELETED: 'NO',
    TITLE: 'LGBTQ una comunidad estoica & resiliente',
    DESCRIPTION: 'TRENDING',
    PODCAST: 'Assets/Podcasts/Podcast/62b107dfe6bcbLGBTQ_Clip_5.mp3',
    IMAGE: 'Assets/Podcasts/Image/62b107dfeaf6brainbow.png',
    PRIVACY: 'PUBLIC',
    IN_LIVE: '',
    BROADCASTER_KEY: '',
    PLAYS: '26',
    FORMAT: 'CLIP',
    CATEGORY: '',
    LISTENED: '',
  },
  {
    ID: '65',
    USER_NAME: 'LALO_MURO',
    DATE_POSTED: '2022-06-20',
    DELETED: 'NO',
    TITLE: 'daddy & mommy issues factor influyente para ser ga',
    DESCRIPTION: 'TRENDING',
    PODCAST: 'Assets/Podcasts/Podcast/62b10cadba095daddy-issues.mp3',
    IMAGE: 'Assets/Podcasts/Image/62b10cadc0129rainbow.png',
    PRIVACY: 'PUBLIC',
    IN_LIVE: '',
    BROADCASTER_KEY: '',
    PLAYS: '24',
    FORMAT: 'CLIP',
    CATEGORY: '',
    LISTENED: '',
  },
  {
    ID: '66',
    USER_NAME: 'LALO_MURO',
    DATE_POSTED: '2022-06-20',
    DELETED: 'NO',
    TITLE: 'Pelicula: La chica danesa ',
    DESCRIPTION: 'TRENDING',
    PODCAST: 'Assets/Podcasts/Podcast/62b10f460d301chica-danesa.mp3',
    IMAGE: 'Assets/Podcasts/Image/62b10f4874ad7rainbow.png',
    PRIVACY: 'PUBLIC',
    IN_LIVE: '',
    BROADCASTER_KEY: '',
    PLAYS: '28',
    FORMAT: 'CLIP',
    CATEGORY: '',
    LISTENED: '',
  },
  {
    ID: '67',
    USER_NAME: 'LALO_MURO',
    DATE_POSTED: '2022-06-20',
    DELETED: 'NO',
    TITLE: 'Pelicula: La chica danesa ',
    DESCRIPTION: 'TRENDING',
    PODCAST: 'Assets/Podcasts/Podcast/62b110762e1dfchica-danesa.mp3',
    IMAGE: 'Assets/Podcasts/Image/62b110773faa7rainbow.png',
    PRIVACY: 'PUBLIC',
    IN_LIVE: '',
    BROADCASTER_KEY: '',
    PLAYS: '19',
    FORMAT: 'CLIP',
    CATEGORY: '',
    LISTENED: '',
  },
  {
    ID: '68',
    USER_NAME: 'LALO_MURO',
    DATE_POSTED: '2022-06-20',
    DELETED: 'NO',
    TITLE: 'Por que decidi grabar este podcast?',
    DESCRIPTION: 'TRENDING',
    PODCAST: 'Assets/Podcasts/Podcast/62b114ccee3a0LGBTQ_Clip_1.mp3',
    IMAGE: 'Assets/Podcasts/Image/62b114ccf10efrainbow.png',
    PRIVACY: 'PUBLIC',
    IN_LIVE: '',
    BROADCASTER_KEY: '',
    PLAYS: '16',
    FORMAT: 'CLIP',
    CATEGORY: '',
    LISTENED: '',
  },
  {
    ID: '69',
    USER_NAME: 'LALO_MURO',
    DATE_POSTED: '2022-06-21',
    DELETED: 'NO',
    TITLE: 'Considerando contar mi historia ',
    DESCRIPTION: 'TRENDING',
    PODCAST: 'Assets/Podcasts/Podcast/62b2926f1ab9fLuna.mp3',
    IMAGE: 'Assets/Podcasts/Image/62b2926f1dab5luna.png',
    PRIVACY: 'PUBLIC',
    IN_LIVE: '',
    BROADCASTER_KEY: '',
    PLAYS: '33',
    FORMAT: 'CLIP',
    CATEGORY: '',
    LISTENED: '',
  },
  {
    ID: '75',
    USER_NAME: 'MY_BOOK',
    DATE_POSTED: '2022-08-29',
    DELETED: 'NO',
    TITLE: 'Quien me llamaba por la noche..?',
    DESCRIPTION: 'te ha pasado que.....',
    PODCAST: 'Assets/Podcasts/Podcast/630d6fcc3c524creepy-1.mp3',
    IMAGE: 'Assets/Podcasts/Image/630d6fcc45f10creepy-1.jpg',
    PRIVACY: 'PUBLIC',
    IN_LIVE: '',
    BROADCASTER_KEY: '',
    PLAYS: '28',
    FORMAT: 'CLIP',
    CATEGORY: 'TERROR',
    LISTENED: '',
  },
  {
    ID: '76',
    USER_NAME: 'MY_BOOK',
    DATE_POSTED: '2022-08-29',
    DELETED: 'NO',
    TITLE: 'Relatos de Policias',
    DESCRIPTION: 'Que pasa en la noche mientras duermes?',
    PODCAST: 'Assets/Podcasts/Podcast/630d72ec9cdcbcreepy-2.mp3',
    IMAGE: 'Assets/Podcasts/Image/630d72eca571dcreepy-2.jpg',
    PRIVACY: 'PUBLIC',
    IN_LIVE: '',
    BROADCASTER_KEY: '',
    PLAYS: '10',
    FORMAT: 'CLIP',
    CATEGORY: 'TERROR',
    LISTENED: '',
  },
  {
    ID: '77',
    USER_NAME: 'MY_BOOK',
    DATE_POSTED: '2022-08-29',
    DELETED: 'NO',
    TITLE: 'Bohemian Grove',
    DESCRIPTION: '',
    PODCAST: 'Assets/Podcasts/Podcast/630d7439ec49ccreepy-3.mp3',
    IMAGE: 'Assets/Podcasts/Image/630d7439eed3fcreepy-3.jpg',
    PRIVACY: 'PUBLIC',
    IN_LIVE: '',
    BROADCASTER_KEY: '',
    PLAYS: '78',
    FORMAT: 'CLIP',
    CATEGORY: 'TERROR',
    LISTENED: '',
  },
];
const VideoGallery: React.FC<IVideoGallery> = ({title}) => {
  return (
    <View style={styles.container}>
      <View>
        <Text style={styles.title}>{title}</Text>
      </View>
      <ScrollView horizontal persistentScrollbar>
        {vds.map(video => (
          <View key={video.ID} style={styles.galeryItem}>
            <ImageBackground
              source={{uri: API_URL + video.IMAGE}}
              style={styles.image}
              resizeMode="cover">
              <Image
                source={require('../../../assets/images/mypodcastmenu/newPodcast.png')}
                style={styles.newBadge}
              />
              <Text>{video.TITLE}</Text>
            </ImageBackground>
          </View>
        ))}
      </ScrollView>
    </View>
  );
};

export default VideoGallery;
